---
fixtures:
  repositories:
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    haveged:
      branch: 5.X
      repo: https://github.com/simp/puppet-haveged
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    krb5: "#{source_dir}"
